version: "3"
services:
  nginx:
    image: nginx:latest
    depends_on:
      - php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "8000:80"
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
      - .:/workspace:cached
  db:
    image: postgres
    volumes:
      - ./docker/pgsql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
